/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 stadium.gltf 
Author: sparshgupta (https://sketchfab.com/SPARSHGUPTA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mini-stadium-800a65b9339940b58939c9c830eaeff7
Title: Mini Stadium
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/stadium.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[14.514, 35.66, 22.679]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Post__Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Post__Black_0_1.geometry} material={materials.Black} />
          <mesh geometry={nodes.Post_Glasss_0.geometry} material={materials.Glasss} />
          <mesh geometry={nodes.MiniStadion008_CRNstoq_0.geometry} material={materials['CRN.stoq']} />
          <mesh geometry={nodes.MiniStadion001_Grass_0.geometry} material={materials.Grass} />
          <mesh geometry={nodes.MiniStadion007_StoneTile_0.geometry} material={materials.StoneTile} />
          <mesh geometry={nodes.MiniStadion006_CRNsetka1_0.geometry} material={materials['CRN.setka1']} />
          <mesh geometry={nodes.MiniStadion006_CRNsetka1_0_1.geometry} material={materials['CRN.setka1']} />
          <mesh geometry={nodes.MiniStadion006_CRNsetka1_0_2.geometry} material={materials['CRN.setka1']} />
          <mesh geometry={nodes.MiniStadion006_CRNsetka1_0_3.geometry} material={materials['CRN.setka1']} />
          <mesh geometry={nodes.MiniStadion006_CRNsetka1_0_4.geometry} material={materials['CRN.setka1']} />
          <mesh geometry={nodes.MiniStadion006_CRNsetka1_0_5.geometry} material={materials['CRN.setka1']} />
          <mesh geometry={nodes['MiniStadion005_CRNMaterial_#1737_0'].geometry} material={materials['CRN.Material_1737']} />
          <mesh geometry={nodes.MiniStadion004_CRNsetka1_0.geometry} material={materials['CRN.setka1']} />
          <mesh geometry={nodes['MiniStadion003_CRNMaterial_#1737_0'].geometry} material={materials['CRN.Material_1737']} />
          <mesh geometry={nodes.MiniStadion002__White_0.geometry} material={materials.White} />
          <mesh geometry={nodes.MiniStadion002__White_0_1.geometry} material={materials.White} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stadium.gltf')
